AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: PHOTO Lambda
Resources:
  indexphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: indexphotos.lambda_handler
      Runtime: python3.7
      CodeUri: ./index-photos-copy
      Description: ""
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::761713908019:role/service-role/index-photos-role-o3x3jya5"
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: upload-photos-bucket
            Events:
              - 's3:ObjectCreated:Put'
      Layers:
        - !Ref MyLayer
  bucket1:
    Type: 'AWS::S3::Bucket'
  searchphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos
      Handler: searchphotos.lambda_handler
      Runtime: python3.7
      CodeUri: ./search-photos-copy
      Description: ""
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::761713908019:role/service-role/search-photos-role"
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      Layers:
        - !Ref MyLayer
        - !Ref MyLayer2
        - 'arn:aws:lambda:us-east-1:406652052116:layer:requests_layer:2'
  MyLayer:
    - 'arn:aws:lambda:us-east-1:761713908019:layer:my-layer:1'
  MyLayer2:
    - 'arn:aws:lambda:us-east-1:761713908019:layer:my-layer2:1'
